CREATE TABLE IF NOT EXISTS cedulas(
  id integer primary key generated by default as identity,
  ncedula bigint,
  nombre text not null check (nombre <> ''),
  apellido text not null check (apellido <> ''),
  lugar_nacimiento text not null,
  sexo text not null,
  estado_civil text not null
);
